defaults:
- _self_
- mode: flexscpack

model: boltz1
use_constraints: false
no_msa: false
# cache: ${hydra:runtime.cwd}/.boltz
cache: /data/localhost/not-backed-up/durant/.boltz

protein_pdb_path: ???
ligand_sdf_path: ???
out_dir: ???
pid: test
ccd: ???
num_iterations: 50 
recycling_steps: 0
sampling_steps: 25
num_samples: 1
lr: 1

hydra:
  run:
    dir: ${out_dir}